/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.utry.erule;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 7;
  /** RegularExpression Id. */
  int KEYWORD = 8;
  /** RegularExpression Id. */
  int LETTER2 = 9;
  /** RegularExpression Id. */
  int DIGIT2 = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<EOL>",
    "<KEYWORD>",
    "<LETTER2>",
    "<DIGIT2>",
    "\"(\"",
    "\")\"",
    "\"AND\"",
    "\"OR\"",
  };

}
